name: 'brazilian_ecommerce_dw'
version: '1.0.0'
config-version: 2

profile: 'brazilian_ecommerce_dw'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  brazilian_ecommerce_dw:
    staging:
      schema: silver
      materialized: view
    intermediate:
      schema: silver
      materialized: view
    marts:
      schema: gold
      materialized: table