version: 2

models:
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: order_status
        tests:
          - not_null
          - accepted_values:
              arguments:
                  values: ['delivered', 'shipped', 'canceled', 'unavailable', 
                       'invoiced', 'processing', 'created', 'approved']

  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: customer_state
        tests:
          - not_null

  - name: stg_order_items
    columns:
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id
  
  - name: stg_geolocation
    columns:
      - name: geolocation_zip_code_prefix
        tests:
         - not_null
  
  - name: stg_order_payments
    columns:
      - name: order_id
        tests:
         - not_null
  - name: stg_order_reviews
    columns:
      - name: order_id
        tests:
         - not_null
  - name: stg_products
    columns:
      - name: product_id
        tests:
         - not_null
         - unique
  - name: stg_sellers
    columns:
      - name: seller_id
        tests:
         - not_null
         - unique
  

